# Site settings
title: Dawsneyland
header-img: img/DSC04616.JPG
email: dawsneyland@gmail.com
copyright_name: Martin Dawson
description: "Dawsneyland exists in the head of Martin Dawson. Here he shares his thoughts and interests."
baseurl: ""
url: "http://www.dawsneyland.com"
twitter_username: dawsneyland
instagram_username:  dawsneyland
youtube_username:  dawsneyland
pinterest_username:  dawsneyland

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
